import React from 'react';
import { useDashboardStore } from '../store/store';
import type { Alert, Emergency, Notification } from '../types/types';

// WebSocket simulation for development
// In production, replace with actual WebSocket connection

type ConnectionStatus = 'connecting' | 'connected' | 'disconnected' | 'error';
type EventHandler = (event: RealTimeEvent) => void;

export interface RealTimeEvent {
    type: 'alert' | 'emergency' | 'notification' | 'metric_update' | 'team_status';
    data: any;
    timestamp: Date;
}

// Mock data generators
const alertTypes = ['SOS Alert', 'Medical Emergency', 'Security Threat', 'Lost Tourist', 'Natural Hazard'];
const locations = ['Taj Mahal, Agra', 'Red Fort, Delhi', 'Gateway of India, Mumbai', 'Hawa Mahal, Jaipur', 'India Gate, Delhi'];
const tourists = ['James Wilson', 'Emma Thompson', 'Robert Chen', 'Maria Garcia', 'David Kim'];

let connectionStatus: ConnectionStatus = 'disconnected';
let statusHandlers: ((status: ConnectionStatus) => void)[] = [];
let eventHandlers: EventHandler[] = [];
let simulationInterval: number | null = null;

const generateRandomAlert = (): Partial<Alert> => {
    const severities: ('critical' | 'high' | 'medium' | 'low')[] = ['critical', 'high', 'medium', 'low'];
    return {
        id: `alert-${Date.now()}`,
        type: alertTypes[Math.floor(Math.random() * alertTypes.length)],
        severity: severities[Math.floor(Math.random() * severities.length)],
        location: locations[Math.floor(Math.random() * locations.length)],
        tourist: tourists[Math.floor(Math.random() * tourists.length)],
        description: 'Automated alert generated by monitoring system',
        status: 'active',
        time: 'Just now',
        createdAt: new Date().toISOString(),
        phone: '+91 98765 43210',
        priority: 1,
        coordinates: `${(20 + Math.random() * 10).toFixed(4)}, ${(72 + Math.random() * 10).toFixed(4)}`,
    };
};

const generateRandomNotification = (): Notification => {
    const types: ('alert' | 'emergency' | 'system' | 'weather')[] = ['alert', 'emergency', 'system', 'weather'];
    const severities: ('critical' | 'warning' | 'info')[] = ['critical', 'warning', 'info'];
    const messages = [
        'New alert received from monitoring station',
        'Team Alpha has arrived at incident location',
        'Emergency resolved successfully',
        'Weather warning issued for coastal areas',
        'Tourist registration spike detected',
        'System backup completed',
    ];

    return {
        id: Date.now(),
        type: types[Math.floor(Math.random() * types.length)],
        severity: severities[Math.floor(Math.random() * severities.length)],
        title: 'System Update',
        message: messages[Math.floor(Math.random() * messages.length)],
        time: 'Just now',
        read: false,
    };
};

const notifyStatusChange = (status: ConnectionStatus) => {
    connectionStatus = status;
    statusHandlers.forEach(handler => handler(status));
};

const emitEvent = (event: RealTimeEvent) => {
    eventHandlers.forEach(handler => handler(event));
};

// Simulate random events
const startSimulation = () => {
    if (simulationInterval) return;

    simulationInterval = window.setInterval(() => {
        const shouldEmit = Math.random() > 0.5;
        if (shouldEmit && connectionStatus === 'connected') {
            const eventType = Math.random() > 0.7 ? 'alert' : 'notification';

            if (eventType === 'alert') {
                const alert = generateRandomAlert();
                emitEvent({ type: 'alert', data: alert, timestamp: new Date() });
                useDashboardStore.getState().addAlert(alert as Alert);
            } else {
                const notification = generateRandomNotification();
                emitEvent({ type: 'notification', data: notification, timestamp: new Date() });
                useDashboardStore.getState().addNotification(notification);
            }
        }
    }, 20000);
};

const stopSimulation = () => {
    if (simulationInterval) {
        clearInterval(simulationInterval);
        simulationInterval = null;
    }
};

export const websocketService = {
    connect: () => {
        if (connectionStatus === 'connected' || connectionStatus === 'connecting') return;

        notifyStatusChange('connecting');

        setTimeout(() => {
            notifyStatusChange('connected');
            startSimulation();

            const notification: Notification = {
                id: Date.now(),
                type: 'system',
                severity: 'info',
                title: 'Connected',
                message: 'Real-time updates are now active',
                time: 'Just now',
                read: false,
            };
            useDashboardStore.getState().addNotification(notification);
        }, 1500);
    },

    disconnect: () => {
        stopSimulation();
        notifyStatusChange('disconnected');
    },

    getStatus: () => connectionStatus,

    onStatusChange: (handler: (status: ConnectionStatus) => void) => {
        statusHandlers.push(handler);
        handler(connectionStatus);
        return () => {
            statusHandlers = statusHandlers.filter(h => h !== handler);
        };
    },

    onEvent: (handler: EventHandler) => {
        eventHandlers.push(handler);
        return () => {
            eventHandlers = eventHandlers.filter(h => h !== handler);
        };
    },

    simulateAlert: () => {
        const alert = generateRandomAlert();
        emitEvent({ type: 'alert', data: alert, timestamp: new Date() });
        useDashboardStore.getState().addAlert(alert as Alert);
    },

    simulateEmergency: () => {
        const emergency: Partial<Emergency> = {
            id: `emerg-${Date.now()}`,
            type: 'Medical Emergency',
            status: 'dispatched',
            location: locations[Math.floor(Math.random() * locations.length)],
            tourist: tourists[Math.floor(Math.random() * tourists.length)],
            assignedTeam: 'Unassigned',
            timeElapsed: 'Just now',
            coordinates: `${(20 + Math.random() * 10).toFixed(4)}, ${(72 + Math.random() * 10).toFixed(4)}`,
        };
        emitEvent({ type: 'emergency', data: emergency, timestamp: new Date() });
    },
};

// React hook for WebSocket
export function useWebSocket() {
    const [status, setStatus] = React.useState<ConnectionStatus>('disconnected');

    React.useEffect(() => {
        const unsubscribe = websocketService.onStatusChange(setStatus);
        websocketService.connect();
        return () => { unsubscribe(); };
    }, []);

    return {
        status,
        isConnected: status === 'connected',
        isConnecting: status === 'connecting',
        connect: websocketService.connect,
        disconnect: websocketService.disconnect,
        simulateAlert: websocketService.simulateAlert,
        simulateEmergency: websocketService.simulateEmergency,
    };
}

export default websocketService;
